return {
  -- "folke/tokyonight.nvim",
  -- name = "tokyonight-monokai",
  -- lazy = false,
  -- priority = 1000,
  -- opts = {},
  -- config = function()
  --   require("tokyonight").setup({
  --     -- use the night style
  --     style = "night",
  --     -- disable italic for functions
  --     styles = {
  --       functions = {},
  --     },
  --     -- Change the "hint" color to the "orange" color, and make the "error" color bright red
  --     on_colors = function(colors)
  --       -- colors.bg = "#1b191b"
  --       -- colors.bg_dark = colors.bg
  --       -- colors.bg_dark1 = colors.bg_dark
  --       -- colors.bg_float = colors.bg_dark
  --     end,
  --     on_highlights = function(highlights, colors)
  --       -- highlights["@lsp.type.string.rust"] = {
  --       --   fg = "#0000ff",
  --       -- }
  --     end,
  --   })
  -- end,
}
